<?php 
define("DB_HOST",'localhost');
define("DB_USER",'db_cro');
//define("DB_USER",'root');
//define('DB_PWD','root');
define('DB_PWD','RbeeiJe2AA3mP7cJ');
define('DB_NAME','db_cro');
define('DB_PORT','3306');
define('DB_TYPE','mysql');
define('DB_CHARSET','utf8');
?>